export interface SeedLead {
  name: string;
  instagram: string; // without @
  city?: string;
  region: string;
  disciplines: string; // comma separated
  notes?: string;
}

// Verified UK / Ireland MMA, Muay Thai & Boxing gym Instagram handles.
// Sourced from public web search results (Instagram profiles + gym websites).
// Each handle was confirmed present on Instagram in the search results.
export const SEED_LEADS: SeedLead[] = [
  // ---------------- MMA ----------------
  {
    name: "Higher Level MMA",
    instagram: "higher_level_mma",
    city: "Glasgow",
    region: "Scotland",
    disciplines: "MMA,Muay Thai",
    notes: "Scotland's top MMA gym. Home to UFC/PFL/Bellator/Cagewarriors fighters. May be above target fame tier.",
  },
  {
    name: "Mark Connor MMA",
    instagram: "mark_connor_mma",
    city: "Glasgow",
    region: "Scotland",
    disciplines: "MMA,Boxing,Wrestling",
    notes: "97 Kingston Street, Glasgow G5 8BJ. Accepting new members. MMA/Boxing/Wrestling/Striking.",
  },
  {
    name: "PKA & C Fit Gym (Punisher Academy)",
    instagram: "punisheracademy",
    city: "Rutherglen",
    region: "Scotland",
    disciplines: "MMA,Kickboxing",
    notes: "Family-run martial arts gym in Glasgow. Kids & adults classes, kickboxing, MMA, PT.",
  },
  {
    name: "Elite Warriors",
    instagram: "elitewarriorsmma",
    city: "Edinburgh",
    region: "Scotland",
    disciplines: "MMA,Muay Thai,Wrestling,BJJ",
    notes: "Edinburgh martial arts gym. Beginners to advanced. MMA, Muay Thai, Wrestling, BJJ.",
  },
  {
    name: "NewLife Gym Glasgow",
    instagram: "newlifegym.mma",
    city: "Glasgow",
    region: "Scotland",
    disciplines: "MMA",
    notes: "Maryhill, Glasgow. Grassroots MMA. Adults, youth, kids & women's-only programs.",
  },
  {
    name: "AVT MMA Leeds",
    instagram: "avtmmaleeds",
    city: "Leeds",
    region: "Yorkshire",
    disciplines: "MMA",
    notes: "Yorkshire's #1 MMA team. Partnered with Gymking & Fight Division.",
  },
  {
    name: "Legends MMA & Fitness Centre",
    instagram: "legendsmma_",
    city: "Leeds",
    region: "Yorkshire",
    disciplines: "MMA",
    notes: "MMA & fitness centre. ~11K followers.",
  },
  {
    name: "1st Legion Gym",
    instagram: "1stlegiongym",
    city: "Leicester",
    region: "Midlands",
    disciplines: "MMA",
    notes: "MMA gym in Leicester city centre. Beginner-friendly, all levels welcome.",
  },
  {
    name: "Team Underground MMA",
    instagram: "teamundergroundmma_official",
    city: "London",
    region: "London",
    disciplines: "MMA,BJJ,Wrestling,Muay Thai,Boxing",
    notes: "181-183 Old Kent Road SE1 5NA. Full combat sports offering. Beginners to pro.",
  },
  {
    name: "Predators MMA & BJJ Academy",
    instagram: "predators_mma_gym",
    city: "Manchester",
    region: "North West",
    disciplines: "MMA,Kickboxing,BJJ",
    notes: "#1 for MMA, Kickboxing & BJJ in Manchester. ~7.5K followers.",
  },
  {
    name: "Team Renegade MMA",
    instagram: "renegadejiujitsu",
    city: "Birmingham",
    region: "Midlands",
    disciplines: "MMA,BJJ",
    notes: "Renegade MMA elite training, Birmingham. UFC/PFL/pro fighters. All levels.",
  },
  {
    name: "Fight Academy Ireland",
    instagram: "fightacademyireland",
    city: "Belfast",
    region: "Northern Ireland",
    disciplines: "MMA",
    notes: "Elite MMA gym in Belfast. Home to world champions & UFC fighter.",
  },
  {
    name: "Ardoyne MMA",
    instagram: "ardoynemma",
    city: "Belfast",
    region: "Northern Ireland",
    disciplines: "MMA,Boxing",
    notes: "North Belfast. Junior MMA events, boxing shows. Teaches fighters from scratch.",
  },
  {
    name: "Fantom Team Ireland",
    instagram: "fantomteamireland",
    city: "Dublin",
    region: "Ireland",
    disciplines: "MMA,BJJ,Wrestling",
    notes: "Dublin. MMA/Hybrid Striking/BJJ/Wrestling/Grappling. First class free.",
  },
  {
    name: "Craig Ewers Academy (CEA)",
    instagram: "craigewersacademy",
    city: "Cardiff",
    region: "Wales",
    disciplines: "MMA,BJJ,Judo",
    notes: "Cardiff CF5 3AU. BJJ, Judo & MMA academy.",
  },
  {
    name: "Hangar HPC",
    instagram: "hangarhpc",
    city: "Cardiff",
    region: "Wales",
    disciplines: "MMA",
    notes: "Multi-sport strength & combat gym, Penarth Road, Cardiff. Purpose-built MMA gym.",
  },

  // ---------------- Muay Thai ----------------
  {
    name: "All Powers Muay Thai Gym",
    instagram: "allpowersgym",
    city: "London",
    region: "London",
    disciplines: "Muay Thai",
    notes: "Head coach 3x world champion. Strength & conditioning area attached. Private 1-2-1 tuition.",
  },
  {
    name: "Weoley Castle Muay Thai",
    instagram: "weoley_castle_muay_thai",
    city: "Birmingham",
    region: "Midlands",
    disciplines: "Muay Thai",
    notes: "Above the Weoley Castle pub, Summerford Road B29 4HA. Kids (5+) & adults classes.",
  },
  {
    name: "Corefit Muay Thai & MMA",
    instagram: "corefituk",
    city: "Sutton Coldfield",
    region: "Midlands",
    disciplines: "Muay Thai,MMA",
    notes: "Muay Thai, MMA, fitness circuits. Adults & kids martial arts gym.",
  },
  {
    name: "2 Technical Muay Thai",
    instagram: "2technicalmuaythai",
    city: "Reddish",
    region: "North West",
    disciplines: "Muay Thai",
    notes: "Muay Thai gym in Reddish, Stockport. Classes & private sessions. Head instructor Paul Karpowicz.",
  },
  {
    name: "Manchester Muay Thai",
    instagram: "manchestermuaythai",
    city: "Manchester",
    region: "North West",
    disciplines: "Muay Thai",
    notes: "Manchester's newest full-time Muay Thai academy. Sister gym to Henshall BJJ.",
  },
  {
    name: "Thai-Tanium Thai Boxing Club",
    instagram: "thaitanium_thai_boxing_club",
    city: "Sileby",
    region: "Midlands",
    disciplines: "Muay Thai",
    notes: "Sileby, central to Leicester & Loughborough. 3,000 sq ft full-time Muay Thai gym. 1:1s, PT, classes.",
  },
  {
    name: "Ronin Muay Thai Gym",
    instagram: "ronin_muaythai_gym",
    city: "Birmingham",
    region: "Midlands",
    disciplines: "Muay Thai",
    notes: "Muay Thai, fitness, self-defence. 1-on-1 coaching, classes, weight loss. B11 1DU.",
  },
  {
    name: "Total Combat Academy",
    instagram: "totalcombatacademy",
    city: "Birmingham",
    region: "Midlands",
    disciplines: "Muay Thai,BJJ,MMA",
    notes: "BJJ, Muay Thai, NUDDA, kids MMA (5-14), combat fit. Runs Muay Thai/K-1 shows.",
  },
  {
    name: "8 Limbs Muay Thai",
    instagram: "8limbsmuaythai",
    city: "London",
    region: "London",
    disciplines: "Muay Thai",
    notes: "Full-time academy dedicated to Muay Thai, 6 days a week. No joining fee. ~5K followers.",
  },
  {
    name: "Black Diamond Gym",
    instagram: "blackdiamondgymuk",
    city: "Birmingham",
    region: "Midlands",
    disciplines: "Muay Thai,Kickboxing",
    notes: "Muay Thai/Kickboxing led by world champion fighters. High-intensity workouts.",
  },
  {
    name: "Bad Company Muay Thai",
    instagram: "badcompanygym",
    city: "Leeds",
    region: "Yorkshire",
    disciplines: "Muay Thai,BJJ,MMA",
    notes: "UK's leading Muay Thai gym, Leeds. 12,000 sq ft, 2 boxing rings. S&C, open mat. (May be high fame.)",
  },
  {
    name: "Keddles Gym",
    instagram: "keddles_gym",
    city: "Dartford",
    region: "South East",
    disciplines: "Boxing,Muay Thai,MMA,BJJ",
    notes: "Orpington/Dartford area. Boxing, Thai boxing, MMA, BJJ. Classes 7 days a week. est. 1994.",
  },

  // ---------------- Boxing ----------------
  {
    name: "Stonebridge Boxing Club",
    instagram: "stonebridgeboxingclub",
    city: "London",
    region: "London",
    disciplines: "Boxing",
    notes: "Boxing gym, Abbey Estate community centre, Queensbury Rd HA0 1NL. All levels.",
  },
  {
    name: "Bakehouse Boxing",
    instagram: "bakehouse_boxing",
    city: "Cardiff",
    region: "Wales",
    disciplines: "Boxing",
    notes: "One of the UK's fastest-growing boxing gyms. Welsh champion & Tri-nations silver medalist.",
  },
  {
    name: "Brighton & Hove Boxing Team",
    instagram: "brightonhoveboxingteam",
    city: "Brighton",
    region: "South East",
    disciplines: "Boxing",
    notes: "Brighton boxing team. ~4.7K followers.",
  },
  {
    name: "Fightr Dublin Boxing Gym",
    instagram: "fightrdublin",
    city: "Dublin",
    region: "Ireland",
    disciplines: "Boxing",
    notes: "Dublin's home of adult boxing. Beginner-friendly. ~22K followers (may be above target tier).",
  },
  {
    name: "BRONX London",
    instagram: "bronxldn",
    city: "London",
    region: "London",
    disciplines: "Boxing",
    notes: "East London boxing gym & studio. Kids programs available.",
  },
  {
    name: "Legions Boxing Club",
    instagram: "legions_boxing_club",
    city: "Manchester",
    region: "North West",
    disciplines: "Boxing",
    notes: "Independent boxing club.",
  },
  {
    name: "O'Tooles Gym",
    instagram: "otoolesgym",
    city: "Manchester",
    region: "North West",
    disciplines: "Boxing",
    notes: "High-end weights facility + professional boxing gym + cardio machines.",
  },
  {
    name: "Derry Mathews Amateur Boxing Club",
    instagram: "derrymathews1",
    city: "Liverpool",
    region: "North West",
    disciplines: "Boxing",
    notes: "Liverpool amateur boxing club. £10/week fitness. Run by Derry Mathews.",
  },
  {
    name: "Mitchell's Boxing Gym",
    instagram: "mitchellboxing_",
    city: "Upminster",
    region: "South East",
    disciplines: "Boxing",
    notes: "Upminster amateur boxing club & elite fitness. ~4K followers.",
  },
  {
    name: "Johnson's Boxing Gym NE15",
    instagram: "johnsons_boxinggym_ne15",
    city: "Newcastle upon Tyne",
    region: "North East",
    disciplines: "Boxing",
    notes: "Lemington, Newcastle NE15. Smaller local gym - good target tier.",
  },
];
